version: "3.9"
services:
  backend:
    container_name: backend_kpd
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend_kpd
    restart: on-failure
    ports:
      - 4000:3000
    env_file: .env
    depends_on:
      - postgres
    networks:
      - backend
    healthcheck:
      test: "wget -nv -t1 --spider 'http://localhost:3000/'"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    container_name: frontend_kpd
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend_kpd
    restart: on-failure
    ports:
      - 8081:80
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    restart: always
    networks:
      - backend
    volumes:
      - postgres_data:/data/postgres

networks:
  backend:
  frontend:

volumes:
  postgres_data:
